Update translate.py
  File "/home/chennb/dev/dev-fra/apps/frappe/frappe/translate.py", line 599, in write_csv_file
    w.writerow([p.encode('utf-8') if p else '', m.encode('utf-8'), t.encode('utf-8')])
TypeError: a bytes-like object is required, not 'str'